#!/usr/bin/env python3
"""extract_schema.py — Step 5 of the domain compiler.

Reads the bundle's product catalog and emits a Pydantic schema of the
likely filter fields. The user is expected to review and commit the
result; this is a one-time bootstrap, not a runtime artifact.

Two strategies, picked via --strategy:

  - llm:  prompt the teacher to read the catalog and emit the schema.
          Best output but needs a teacher key.
  - infer: deterministic — walk the catalog, find every attribute /
           spec key, infer types from the values, emit a Pydantic
           model. Works with no API key. Lower quality, but a strong
           starting point.

The default is `infer`. The LLM version is the polish pass.

Usage:
    python scripts/extract_schema.py --bundle artifacts/skis
    python scripts/extract_schema.py --bundle artifacts/skis --strategy llm
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from shared.domain_bundle import Bundle  # noqa: E402

logger = logging.getLogger("extract_schema")


# ---------------------------------------------------------------------------
# Inference strategy — deterministic, no API.
# ---------------------------------------------------------------------------
def infer_schema(products: list[dict], domain: str) -> str:
    """Produce a Pydantic schema by walking the catalog."""
    by_field: dict[str, list[Any]] = {}
    for p in products:
        for k, v in (p.get("specs") or {}).items():
            by_field.setdefault(k, []).append(v)
        for k, v in (p.get("attributes") or {}).items():
            by_field.setdefault(k, []).append(v)

    fields: list[tuple[str, str, str | None]] = []  # (name, py_type, comment)
    for field, values in sorted(by_field.items()):
        py_type, comment = _infer_field_type(field, values)
        if py_type:
            fields.append((field, py_type, comment))
    # Add the obvious commerce field by hand if not already present.
    if not any(f[0] == "price_max" for f in fields):
        fields.append(("price_max", "Optional[float] = None", "added by extract_schema"))

    return _render_pydantic(domain, fields)


def _infer_field_type(field: str, values: list[Any]) -> tuple[str, str | None]:
    """Pick a Pydantic type annotation for one field given its values."""
    non_null = [v for v in values if v is not None]
    if not non_null:
        return "", None

    if all(isinstance(v, bool) for v in non_null):
        return "Optional[bool] = None", None
    if all(isinstance(v, int) and not isinstance(v, bool) for v in non_null):
        # If the field name has _mm or _g suffix it's clearly numeric;
        # we generate _min/_max range fields from it.
        if any(field.endswith(s) for s in ("_mm", "_g", "_cm", "_m")):
            base = field
            return (
                f"# range filter; emit both bounds:\n"
                f"    {base}_min: Optional[int] = None\n"
                f"    {base}_max: Optional[int] = None",
                "auto-generated as range",
            )
        return "Optional[int] = None", None
    if all(isinstance(v, (int, float)) for v in non_null):
        return "Optional[float] = None", None
    if all(isinstance(v, str) for v in non_null):
        # Categorical with a small set → Literal
        unique = sorted(set(str(v) for v in non_null))
        if 1 < len(unique) <= 16:
            tags = ", ".join(f'"{t}"' for t in unique)
            return f"Optional[Literal[{tags}]] = None", None
        return "Optional[str] = None", None
    if all(isinstance(v, list) for v in non_null):
        # List of categoricals → flatten and use Literal
        flat = []
        for lst in non_null:
            for x in lst:
                if isinstance(x, str):
                    flat.append(x)
        unique = sorted(set(flat))
        if 1 < len(unique) <= 32:
            tags = ", ".join(f'"{t}"' for t in unique)
            return f"Optional[list[Literal[{tags}]]] = None", None
        return "Optional[list[str]] = None", None
    return "Optional[Any] = None", None


def _render_pydantic(domain: str, fields: list[tuple[str, str, str | None]]) -> str:
    capital = "".join(w.capitalize() for w in domain.replace("-", "_").split("_"))
    cls_name = f"{capital}Query"
    lines: list[str] = [
        '"""Auto-generated filter schema for the {} domain.'.format(domain),
        '',
        'Generated by scripts/extract_schema.py. Edit then commit.',
        '"""',
        '',
        'from typing import Any, Literal, Optional',
        '',
        'from pydantic import BaseModel, Field',
        '',
        '',
        f'class {cls_name}(BaseModel):',
    ]
    if not fields:
        lines.append('    """No filterable fields detected."""')
        lines.append('    pass')
    for name, type_str, comment in fields:
        if "\n" in type_str:
            # Range fields render as a comment + two field lines.
            # The first line is a `#` comment; subsequent lines are
            # already shaped as `field: type` (no extra indent needed).
            for sub in type_str.splitlines():
                # The leading 4-space indent on `sub` (from the upstream
                # generator) belongs to a class body but extract_schema
                # double-indents it. Strip it so we render at the same
                # level as ordinary fields.
                lines.append(f"    {sub.lstrip()}")
        else:
            suffix = f"  # {comment}" if comment else ""
            lines.append(f"    {name}: {type_str}{suffix}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# LLM strategy — pass the catalog to the teacher.
# ---------------------------------------------------------------------------
LLM_SYSTEM = (
    "You are a Pydantic schema generator. Read a product catalog and "
    "emit a Python file containing one Pydantic model named "
    "<DomainName>Query whose fields cover the likely filter dimensions "
    "the user might constrain. Use Optional[...] for every field, "
    "Literal[...] for closed categoricals, and emit min/max pairs for "
    "numeric ranges. Output Python source code only — no fences, no "
    "prose."
)


def llm_schema(products: list[dict], domain: str) -> str:
    from shared.llm_provider import get_provider
    provider = get_provider()
    catalog_excerpt = json.dumps(products[: min(10, len(products))], indent=2)
    prompt = (
        f"{LLM_SYSTEM}\n\n"
        f"Domain: {domain}\n"
        f"First 10 products:\n{catalog_excerpt}\n\n"
        f"Emit the Python file."
    )
    text = provider.generate(prompt, json_mode=False)
    # Strip code fences if the model added them despite instructions.
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith(("python", "py")):
            text = text.split("\n", 1)[1] if "\n" in text else ""
    return text.strip() + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", required=True)
    parser.add_argument(
        "--strategy", choices=["infer", "llm"], default="infer",
        help="schema generation strategy",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(name)s: %(message)s",
    )

    bundle = Bundle.load(args.bundle)
    products = bundle.read_products()
    if not products:
        logger.error("bundle has no products; can't infer a schema")
        return 2

    if args.strategy == "llm":
        schema_src = llm_schema(products, bundle.manifest.domain)
    else:
        schema_src = infer_schema(products, bundle.manifest.domain)

    bundle.paths.schema_py.write_text(schema_src)
    logger.info("wrote %s (%d bytes)", bundle.paths.schema_py, len(schema_src))
    print(schema_src)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
